# Copyright 2026 PeopleWare N.V.
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = ["package.json", "package-lock.json", "tests/__snapshots__/**", "NOTICE", ".nvmrc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 PeopleWare N.V."
SPDX-License-Identifier = "Apache-2.0"
